# Generated by Django 3.0.8 on 2020-09-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turnos',
            new_name='Turno',
        ),
    ]
