# Generated by Django 3.0.8 on 2020-09-12 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20200905_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='idproveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.Proveedor'),
        ),
    ]
