# Generated by Django 3.0.8 on 2020-09-13 00:25

from django.db import migrations, models
import turnos.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_auto_20200912_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='turno',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_solicitud',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_turno',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='idcliente',
            field=models.IntegerField(null=True, verbose_name=turnos.models.Cliente),
        ),
    ]
