# Generated by Django 3.0.8 on 2020-09-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_auto_20200912_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='idcliente',
            field=models.IntegerField(null=True),
        ),
    ]
