# Generated by Django 3.0.8 on 2020-09-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_auto_20200912_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='idcliente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
