# Generated by Django 3.0.8 on 2020-09-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_auto_20200912_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='idcliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.Cliente'),
        ),
    ]
